[REGRESSION] content_from_pid can't resolve map in all cases
T3Voila/templavoilaplus pull request #345
Opened 2022-04-28 12:05 UTC by jpmschuler

If the main page (uid 123) which defines the map has a subpage (uid 456) and uses
"content_from_pid" to point to that subpage the page cannot be rendered.

The record is the subpage record (456), the rootline is the mainPage rootline. However while
getting map from rootline the first element is skipped as it is the current page in most cases.

This patch removes that skipping, as it is barely slower and allows to identify the parent map
in a content_from_pid case.

2022-05-02 08:55 UTC, jpmschuler commented
the $isFirst can't be removed ... as the meaning of the next_map field

2022-05-03 15:51 UTC, jpmschuler commented
Ok, went to the drawing board and came up with that the map really needs to stay from the original uid rather than being loaded from target uid, even if we get the content from a different pid. As we want content, not the map/template/whatever.

This sounds like it could create race conditions with different maps of source and target but
a) this resolves a lot of other issues (like the above one with same map)
b) the amount of race conditions is lower

So there are still options where target map defines content areas which the original map doesn't have, but then it would be reasonable to only show those which match. So in the end this approach is easier, more streamlined and more compatible

2022-05-03 19:37 UTC, opi99 requested changes
Sounds fine for me.
BTW same issue if you use the MountPoint type ... use template info from orig or from target ;-)

2022-05-03 19:37 UTC, opi99 commented on Classes/Controller/Frontend/FrontendController.php
> +            while($pageRecord['content_from_pid']) {
missing white space after while

2022-05-04 13:44 UTC, jpmschuler commented
Replaced the while to chain `content_from_pid` with a if, as the while had some regression in seldom cases (e.g. self-referencing cfp). 
And before making an analysis of all the cases just forbidding a chained `content_from_pid` seems reasonable.

2022-05-05 08:38 UTC, opi99 requested changes
Please following
* Only changes for the feature/bugfix and no changes in nearbe code
* If you break function calls then in following way
methodName(
    $param1,
    $param2
);
* No extra spaces in comments for align type / argument names
* IMHO Both should be hinted by PSR and are standard inside TYPO3

2022-05-05 08:46 UTC, jpmschuler commented
Sry, cherrypicked from wrong branch - still activating and deactivating code style rules by branches locally until everything is merged

2022-05-05 09:10 UTC, jpmschuler commented
(As phpdoc alignment is not specified in PSR1/2 nor in TYPO3 coding standards, added enforcement to #354 via 469bb1a70e0a1b880e7e436b3df1ecd2dfd7bfe8)

2022-05-06 16:24 UTC, opi99 approved these changes

2022-05-06 16:24 UTC, merged