[FEATURE] add basic code quality checks via composer scripts and github actions
T3Voila/templavoilaplus pull request #349
Opened 2022-05-03 15:56 UTC by jpmschuler

EXT:tea offers the results of the TYPO3 QA-Initiative for extensions, we should copy all that knowledge to have a defined code style which all IDEs pick up on, as well as have github actions auto-check code for incoming PRs.

Of course afterwards it will take some effort until everything is green for the first time, but having tools fix style is always a good choice.

This PR just adds the tools and CI/CD actions, it doesn't change the code itself.

2022-05-03 19:21 UTC, opi99 requested changes
Do we need to mess inside the Resources/Private directory?

npm/yarn for what?

Does it need the /tools directory?

2022-05-03 19:21 UTC, opi99 commented on Classes/Utility/ApiHelperUtility.php
> +        if (strpos($combinedConfigurationIdentifier,':') === false) {
Missing space after comma.

2022-05-03 19:37 UTC, jpmschuler commented
> Do we need to mess inside the Resources/Private directory?
No, fixed. Thought so too, changed EXT:tea: https://github.com/TYPO3-Documentation/tea/pull/445

> npm/yarn for what?
eslint and stylelint, the tools for fixing JS and CSS code style

> Does it need the /tools directory?
yes for the few tools that aren't manageable by composer and npm. There is a long discussion in the QA-team about that, but at least it is down to these few instead of everything. 

I'd say: stick to their long discussed standards instead of re-inventing the wheel.

2022-05-03 19:38 UTC, jpmschuler commented on Classes/Utility/ApiHelperUtility.php
> +        if (strpos($combinedConfigurationIdentifier,':') === false) {
done

2022-05-04 08:41 UTC, opi99 approved these changes

2022-05-04 08:42 UTC, merged