[CODESTYLE] fix codestyle for xliff, up to xliff v1.2
T3Voila/templavoilaplus pull request #357
Opened 2022-05-04 12:53 UTC by jpmschuler

As requested without resorting the labels. 
(I physically hurt to deactivate the option, but better green tests than long discussions)

2022-05-05 09:28 UTC, opi99 requested changes
Do we need to convert &quot; to &#34;?
Do we need to convert ' to &#39;?
Maybe put the xsd into tools folder instead of downloading it every time

2022-05-05 11:11 UTC, jpmschuler commented
More pessimistic changes; linter still green.

2022-05-06 17:50 UTC, opi99 approved these changes

2022-05-06 17:55 UTC, opi99 approved these changes

2022-05-06 17:56 UTC, merged